/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
/* Generated at           Jul 19 2025 19:32:36 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\matrices/includes -g -fmf -o buscarEnMatriz.exe C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Jul 19 2025 19:32:36"
#define  COB_MODULE_DATE		20250719
#define  COB_MODULE_TIME		193236

/* Global variables */
#include "buscarEnMatriz.c.h"

/* Function prototypes */

static int		MATRICES ();
static int		MATRICES_ (const int);
static void		MATRICES_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (MATRICES ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MATRICES' */

/* ENTRY 'MATRICES' */

static int
MATRICES ()
{
  return MATRICES_ (0);
}

static int
MATRICES_ (const int entry)
{
  /* Program local variables */
  #include "buscarEnMatriz.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 32        : Entry     MATRICES                : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
  l_2:;
#line 32 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  ENTRY_MATRICES:	cob_nop ();
#line 109 "buscarEnMatriz.c"

  /* Line: 32        : Section   MAIN-PROGRAM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 32 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  SECTION_MAIN__PROGRAM:	cob_nop ();
#line 114 "buscarEnMatriz.c"

  /* Line: 33        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 33 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 119 "buscarEnMatriz.c"
  for (;;)
  {
    /* Line: 33        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 33 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 125 "buscarEnMatriz.c"
    if (((int)cob_cmp_numdisp (b_22, 1, 5LL, 0) == 0))
      break;

    /* Line: 34        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 34 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 132 "buscarEnMatriz.c"
    /* PERFORM MAIN-MENU */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_16;
    goto l_6;
    l_16:
    frame_ptr--;

    /* Line: 35        : EVALUATE           : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 35 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 146 "buscarEnMatriz.c"

    /* Line: 36        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 36 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 151 "buscarEnMatriz.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 1LL, 0) == 0))
    {

      /* Line: 37        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 37 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 159 "buscarEnMatriz.c"
      /* PERFORM DIMENSIONAR-MATRICES */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 8;
      frame_ptr->return_address_ptr = &&l_17;
      goto l_8;
      l_17:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 38        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 38 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 175 "buscarEnMatriz.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 2LL, 0) == 0))
    {

      /* Line: 39        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 39 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 183 "buscarEnMatriz.c"
      /* PERFORM CARGAR-MATRICES */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 10;
      frame_ptr->return_address_ptr = &&l_18;
      goto l_10;
      l_18:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 40        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 40 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 199 "buscarEnMatriz.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 3LL, 0) == 0))
    {

      /* Line: 41        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 41 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 207 "buscarEnMatriz.c"
      /* PERFORM SUMAR-MATRICES */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 12;
      frame_ptr->return_address_ptr = &&l_19;
      goto l_12;
      l_19:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 42        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 42 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 223 "buscarEnMatriz.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 4LL, 0) == 0))
    {

      /* Line: 43        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 43 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 231 "buscarEnMatriz.c"
      /* PERFORM BUSCAR-IGUALES */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 14;
      frame_ptr->return_address_ptr = &&l_20;
      goto l_14;
      l_20:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 44        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 44 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 247 "buscarEnMatriz.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 5LL, 0) == 0))
    {

      /* Line: 45        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 45 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 255 "buscarEnMatriz.c"
      cob_display (0, 1, 1, &c_1);
      goto l_5;
    }

    /* WHEN OTHER */

    /* Line: 47        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 47 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 265 "buscarEnMatriz.c"
    cob_display (0, 1, 1, &c_2);

    /* End EVALUATE */
    l_5:;
  }

  /* Line: 50        : STOP RUN           : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 50 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 275 "buscarEnMatriz.c"
  cob_stop_run (b_2);

  /* Line: 55        : Section   MAIN-MENU               : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
  l_6:;
#line 55 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  SECTION_MAIN__MENU:	cob_nop ();
#line 282 "buscarEnMatriz.c"

  /* Line: 56        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 56 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 287 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 57        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 57 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 293 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_4);

  /* Line: 58        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 58 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 299 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_5);

  /* Line: 59        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 59 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 305 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_6);

  /* Line: 60        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 60 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 311 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_7);

  /* Line: 61        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 61 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 317 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_8);

  /* Line: 62        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 62 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 323 "buscarEnMatriz.c"
  cob_display (0, 0, 1, &c_9);

  /* Line: 63        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 63 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 329 "buscarEnMatriz.c"
  cob_accept (&f_22);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 66        : Section   DIMENSIONAR-MATRICES    : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
  l_8:;
#line 66 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  SECTION_DIMENSIONAR__MATRICES:	cob_nop ();
#line 340 "buscarEnMatriz.c"

  /* Line: 67        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 67 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 345 "buscarEnMatriz.c"
  for (;;)
  {
    /* Line: 67        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 67 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 351 "buscarEnMatriz.c"
    if ((((int)cob_cmp_numdisp (b_17, 2, 1LL, 0) >= 0) && 
        ((int)cob_cmp_numdisp (b_17, 2, 10LL, 0) <= 0)))
      break;

    /* Line: 68        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 68 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 359 "buscarEnMatriz.c"
    cob_display (0, 1, 1, &c_10);

    /* Line: 69        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 69 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 365 "buscarEnMatriz.c"
    cob_accept (&f_17);

    /* Line: 70        : IF                 : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 70 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 371 "buscarEnMatriz.c"
    if ((((int)cob_cmp_numdisp (b_17, 2, 10LL, 0) > 0) || 
        ((int)cob_cmp_numdisp (b_17, 2, 1LL, 0) < 0)))
    {

      /* Line: 71        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 71 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 379 "buscarEnMatriz.c"
      cob_display (0, 1, 1, &c_11);
    }
  }

  /* Line: 75        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 75 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 387 "buscarEnMatriz.c"
  for (;;)
  {
    /* Line: 75        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 75 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 393 "buscarEnMatriz.c"
    if ((((int)cob_cmp_numdisp (b_18, 2, 1LL, 0) >= 0) && 
        ((int)cob_cmp_numdisp (b_18, 2, 10LL, 0) <= 0)))
      break;

    /* Line: 76        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 76 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 401 "buscarEnMatriz.c"
    cob_display (0, 1, 1, &c_12);

    /* Line: 77        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 77 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 407 "buscarEnMatriz.c"
    cob_accept (&f_18);

    /* Line: 78        : IF                 : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 78 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 413 "buscarEnMatriz.c"
    if ((((int)cob_cmp_numdisp (b_18, 2, 10LL, 0) > 0) || 
        ((int)cob_cmp_numdisp (b_18, 2, 1LL, 0) < 0)))
    {

      /* Line: 79        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 79 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 421 "buscarEnMatriz.c"
      cob_display (0, 1, 1, &c_11);
    }
  }

  /* Line: 82        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 82 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 429 "buscarEnMatriz.c"
  cob_display (0, 1, 4, &c_13, &f_17, &c_14, &f_18);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 84        : Section   CARGAR-MATRICES         : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
  l_10:;
#line 84 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  SECTION_CARGAR__MATRICES:	cob_nop ();
#line 440 "buscarEnMatriz.c"

  /* Line: 85        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 85 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 445 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_15);

  /* Line: 86        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 86 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 451 "buscarEnMatriz.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 86        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 86 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 458 "buscarEnMatriz.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 87        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 87 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 465 "buscarEnMatriz.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 87        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 87 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 472 "buscarEnMatriz.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 88        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 88 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 479 "buscarEnMatriz.c"
      cob_display (0, 1, 5, &c_16, &f_19, &c_17, &f_20, &c_18);

      /* Line: 89        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 89 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 485 "buscarEnMatriz.c"
      cob_accept (&f_21);

      /* Line: 90        : MOVE               : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 90 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 491 "buscarEnMatriz.c"
      memcpy (b_24 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), b_21, 3);
      /* Line: 87        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 87 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 496 "buscarEnMatriz.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 86        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 86 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 502 "buscarEnMatriz.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Line: 95        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 95 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 509 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_19);

  /* Line: 96        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 96 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 515 "buscarEnMatriz.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 96        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 96 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 522 "buscarEnMatriz.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 97        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 97 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 529 "buscarEnMatriz.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 97        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 97 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 536 "buscarEnMatriz.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 98        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 98 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 543 "buscarEnMatriz.c"
      cob_display (0, 1, 5, &c_16, &f_19, &c_17, &f_20, &c_20);

      /* Line: 99        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 99 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 549 "buscarEnMatriz.c"
      cob_accept (&f_21);

      /* Line: 100       : MOVE               : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 100 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 555 "buscarEnMatriz.c"
      memcpy (b_28 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), b_21, 3);
      /* Line: 97        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 97 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 560 "buscarEnMatriz.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 96        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 96 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 566 "buscarEnMatriz.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 104       : Section   SUMAR-MATRICES          : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
  l_12:;
#line 104 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  SECTION_SUMAR__MATRICES:	cob_nop ();
#line 578 "buscarEnMatriz.c"

  /* Line: 105       : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 105 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 583 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_21);

  /* Line: 106       : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 106 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 589 "buscarEnMatriz.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 106       : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 106 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 596 "buscarEnMatriz.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 107       : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 107 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 603 "buscarEnMatriz.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 107       : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 107 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 610 "buscarEnMatriz.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 108       : COMPUTE            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 108 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 617 "buscarEnMatriz.c"
      cob_decimal_set_field (d_0, COB_SET_FLD (f0, 3, b_24 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4));
      cob_decimal_set_field (d_1, COB_SET_FLD (f0, 3, b_28 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4));
      cob_decimal_add (d_0, d_1);
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 3, b_32 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4), 0);

      /* Line: 109       : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 109 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 626 "buscarEnMatriz.c"
      cob_display (0, 1, 6, &c_22, &f_19, &c_17, &f_20, &c_23, COB_SET_FLD (f0, 3, b_32 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4));
      /* Line: 107       : VARYING            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 107 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 631 "buscarEnMatriz.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 106       : VARYING            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 106 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 637 "buscarEnMatriz.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 114       : Section   BUSCAR-IGUALES          : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
  l_14:;
#line 114 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  SECTION_BUSCAR__IGUALES:	cob_nop ();
#line 649 "buscarEnMatriz.c"

  /* Line: 115       : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 115 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 654 "buscarEnMatriz.c"
  cob_display (0, 1, 1, &c_24);

  /* Line: 116       : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 116 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 660 "buscarEnMatriz.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 116       : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 116 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 667 "buscarEnMatriz.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 117       : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 117 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 674 "buscarEnMatriz.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 117       : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 117 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 681 "buscarEnMatriz.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 118       : IF                 : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 118 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 688 "buscarEnMatriz.c"
      if (((int)memcmp (b_24 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), b_28 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), 3) == 0))
      {

        /* Line: 119       : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 119 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
        cob_nop ();
#line 695 "buscarEnMatriz.c"
        cob_display (0, 1, 6, &c_25, &f_19, &c_26, &f_20, &c_23, COB_SET_FLD (f0, 3, b_24 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4));
      }
      /* Line: 117       : VARYING            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 117 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 701 "buscarEnMatriz.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 116       : VARYING            : C:\msys64\home\lopez\COBOL\matrices\buscarEnMatriz.cbl */
#line 116 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
    cob_nop ();
#line 707 "buscarEnMatriz.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 14)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  MATRICES_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field N */
#line 7 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 765 "buscarEnMatriz.c"
  memset (b_17, 48, 2);

  /* initialize field M */
#line 8 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 771 "buscarEnMatriz.c"
  memset (b_18, 48, 2);

  /* initialize field I */
#line 9 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 777 "buscarEnMatriz.c"
  memset (b_19, 48, 2);

  /* initialize field J */
#line 10 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 783 "buscarEnMatriz.c"
  memset (b_20, 48, 2);

  /* initialize field NUM */
#line 11 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 789 "buscarEnMatriz.c"
  memset (b_21, 48, 3);

  /* initialize field WS-OPCION */
#line 12 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 795 "buscarEnMatriz.c"
  *(b_22) = 48;

  /* initialize field VALOR-VALIDO */
#line 13 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
  cob_nop ();
#line 801 "buscarEnMatriz.c"
  *(cob_u8_ptr)(b_23) = (unsigned char)'N';

  /* initialize ROW-1: init first record */
  {
    /* initialize COL-1: init first record */
    {
      /* initialize field ELEM-1 */
#line 19 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 811 "buscarEnMatriz.c"
      memset (b_24, 48, 3);
      /* initialize COL-1: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_24;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-1:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-1:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-1:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-1:     9 thru 10 */
      }
    }
    /* initialize ROW-1: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_24;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-1:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-1:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-1:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-1:     9 thru 10 */
    }
  }

  /* initialize ROW-2: init first record */
  {
    /* initialize COL-2: init first record */
    {
      /* initialize field ELEM-2 */
#line 24 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 839 "buscarEnMatriz.c"
      memset (b_28, 48, 3);
      /* initialize COL-2: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_28;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-2:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-2:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-2:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-2:     9 thru 10 */
      }
    }
    /* initialize ROW-2: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_28;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-2:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-2:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-2:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-2:     9 thru 10 */
    }
  }

  /* initialize ROW-3: init first record */
  {
    /* initialize COL-3: init first record */
    {
      /* initialize field ELEM-3 */
#line 29 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\buscarEnMatriz.cbl"
      cob_nop ();
#line 867 "buscarEnMatriz.c"
      memset (b_32, 48, 3);
      /* initialize COL-3: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_32;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-3:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-3:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-3:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-3:     9 thru 10 */
      }
    }
    /* initialize ROW-3: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_32;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-3:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-3:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-3:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-3:     9 thru 10 */
    }
  }


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'MATRICES' */

/* Initialize module structure for MATRICES */
static void MATRICES_module_init (cob_module *module)
{
  module->module_name = "MATRICES";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MATRICES;
  module->module_cancel.funcptr = (void *(*)())MATRICES_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

