/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
/* Generated at           Jul 19 2025 16:45:30 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\matrices/includes -g -fmf -o matrizDiagonal.exe C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */

/* Program local variables for 'MATRICES' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[2] __attribute__((aligned));	/* N */
static cob_u8_t	b_18[2] __attribute__((aligned));	/* I */
static cob_u8_t	b_19[2] __attribute__((aligned));	/* J */
static cob_u8_t	b_20[3] __attribute__((aligned));	/* NUM */
static cob_u8_t	b_21[1] __attribute__((aligned));	/* WS-OPCION */
static cob_u8_t	b_22[4] __attribute__((aligned));	/* ACUMULADOR */
static cob_u8_t	b_23[300] __attribute__((aligned));	/* MATRIX-1 */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {2, b_17, &a_3};	/* N */
static cob_field f_18	= {2, b_18, &a_3};	/* I */
static cob_field f_19	= {2, b_19, &a_3};	/* J */
static cob_field f_20	= {3, b_20, &a_4};	/* NUM */
static cob_field f_21	= {1, b_21, &a_2};	/* WS-OPCION */
static cob_field f_22	= {4, b_22, &a_5};	/* ACUMULADOR */

/* End of fields */

