/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
/* Generated at           Jul 19 2025 16:45:30 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\matrices/includes -g -fmf -o matrizDiagonal.exe C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Jul 19 2025 16:45:30"
#define  COB_MODULE_DATE		20250719
#define  COB_MODULE_TIME		164530

/* Global variables */
#include "matrizDiagonal.c.h"

/* Function prototypes */

static int		MATRICES ();
static int		MATRICES_ (const int);
static void		MATRICES_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (MATRICES ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MATRICES' */

/* ENTRY 'MATRICES' */

static int
MATRICES ()
{
  return MATRICES_ (0);
}

static int
MATRICES_ (const int entry)
{
  /* Program local variables */
  #include "matrizDiagonal.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 22        : Entry     MATRICES                : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
  l_2:;
#line 22 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  ENTRY_MATRICES:	cob_nop ();
#line 105 "matrizDiagonal.c"

  /* Line: 22        : Section   MAIN-PROGRAM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 22 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  SECTION_MAIN__PROGRAM:	cob_nop ();
#line 110 "matrizDiagonal.c"

  /* Line: 23        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 23 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 115 "matrizDiagonal.c"
  for (;;)
  {
    /* Line: 23        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 23 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 121 "matrizDiagonal.c"
    if (((int)cob_cmp_numdisp (b_21, 1, 4LL, 0) == 0))
      break;

    /* Line: 24        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 24 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 128 "matrizDiagonal.c"
    /* PERFORM MAIN-MENU */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_6;
    l_14:
    frame_ptr--;

    /* Line: 25        : EVALUATE           : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 25 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 142 "matrizDiagonal.c"

    /* Line: 26        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 26 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 147 "matrizDiagonal.c"

    if (((int)cob_cmp_numdisp (b_21, 1, 1LL, 0) == 0))
    {

      /* Line: 27        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 27 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 155 "matrizDiagonal.c"
      /* PERFORM DIMENSIONAR-MATRIZ */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 8;
      frame_ptr->return_address_ptr = &&l_15;
      goto l_8;
      l_15:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 28        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 28 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 171 "matrizDiagonal.c"

    if (((int)cob_cmp_numdisp (b_21, 1, 2LL, 0) == 0))
    {

      /* Line: 29        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 29 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 179 "matrizDiagonal.c"
      /* PERFORM CARGAR-MATRICES */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 10;
      frame_ptr->return_address_ptr = &&l_16;
      goto l_10;
      l_16:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 30        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 30 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 195 "matrizDiagonal.c"

    if (((int)cob_cmp_numdisp (b_21, 1, 3LL, 0) == 0))
    {

      /* Line: 31        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 31 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 203 "matrizDiagonal.c"
      /* PERFORM SUMAR-DIAGONAL */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 12;
      frame_ptr->return_address_ptr = &&l_17;
      goto l_12;
      l_17:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 32        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 32 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 219 "matrizDiagonal.c"

    if (((int)cob_cmp_numdisp (b_21, 1, 4LL, 0) == 0))
    {

      /* Line: 33        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 33 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 227 "matrizDiagonal.c"
      cob_display (0, 1, 1, &c_1);
      goto l_5;
    }

    /* WHEN OTHER */

    /* Line: 35        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 35 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 237 "matrizDiagonal.c"
    cob_display (0, 1, 1, &c_2);

    /* End EVALUATE */
    l_5:;
  }

  /* Line: 38        : STOP RUN           : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 38 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 247 "matrizDiagonal.c"
  cob_stop_run (b_2);

  /* Line: 42        : Section   MAIN-MENU               : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
  l_6:;
#line 42 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  SECTION_MAIN__MENU:	cob_nop ();
#line 254 "matrizDiagonal.c"

  /* Line: 43        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 43 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 259 "matrizDiagonal.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 44        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 44 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 265 "matrizDiagonal.c"
  cob_display (0, 1, 1, &c_4);

  /* Line: 45        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 45 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 271 "matrizDiagonal.c"
  cob_display (0, 1, 1, &c_5);

  /* Line: 46        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 46 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 277 "matrizDiagonal.c"
  cob_display (0, 1, 1, &c_6);

  /* Line: 47        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 47 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 283 "matrizDiagonal.c"
  cob_display (0, 1, 1, &c_7);

  /* Line: 48        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 48 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 289 "matrizDiagonal.c"
  cob_display (0, 0, 1, &c_8);

  /* Line: 49        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 49 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 295 "matrizDiagonal.c"
  cob_accept (&f_21);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 52        : Section   DIMENSIONAR-MATRIZ      : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
  l_8:;
#line 52 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  SECTION_DIMENSIONAR__MATRIZ:	cob_nop ();
#line 306 "matrizDiagonal.c"

  /* Line: 53        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 53 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 311 "matrizDiagonal.c"
  for (;;)
  {
    /* Line: 53        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 53 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 317 "matrizDiagonal.c"
    if ((((int)cob_cmp_numdisp (b_17, 2, 1LL, 0) >= 0) && 
        ((int)cob_cmp_numdisp (b_17, 2, 10LL, 0) <= 0)))
      break;

    /* Line: 54        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 54 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 325 "matrizDiagonal.c"
    cob_display (0, 1, 1, &c_9);

    /* Line: 55        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 55 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 331 "matrizDiagonal.c"
    cob_accept (&f_17);

    /* Line: 56        : IF                 : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 56 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 337 "matrizDiagonal.c"
    if ((((int)cob_cmp_numdisp (b_17, 2, 10LL, 0) > 0) || 
        ((int)cob_cmp_numdisp (b_17, 2, 1LL, 0) < 0)))
    {

      /* Line: 57        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 57 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 345 "matrizDiagonal.c"
      cob_display (0, 1, 1, &c_10);
    }
  }

  /* Line: 60        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 60 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 353 "matrizDiagonal.c"
  cob_display (0, 1, 4, &c_11, &f_17, &c_12, &f_17);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 62        : Section   CARGAR-MATRICES         : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
  l_10:;
#line 62 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  SECTION_CARGAR__MATRICES:	cob_nop ();
#line 364 "matrizDiagonal.c"

  /* Line: 63        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 63 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 369 "matrizDiagonal.c"
  cob_display (0, 1, 1, &c_13);

  /* Line: 64        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 64 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 375 "matrizDiagonal.c"
  memcpy (b_18, "01", 2);
  for (;;)
  {
    /* Line: 64        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 64 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 382 "matrizDiagonal.c"
    if (((int)memcmp (b_18, b_17, 2) > 0))
      break;

    /* Line: 65        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 65 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 389 "matrizDiagonal.c"
    memcpy (b_19, "01", 2);
    for (;;)
    {
      /* Line: 65        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 65 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 396 "matrizDiagonal.c"
      if (((int)memcmp (b_19, b_17, 2) > 0))
        break;

      /* Line: 66        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 66 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 403 "matrizDiagonal.c"
      cob_display (0, 1, 5, &c_14, &f_18, &c_15, &f_19, &c_16);

      /* Line: 67        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 67 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 409 "matrizDiagonal.c"
      cob_accept (&f_20);

      /* Line: 68        : MOVE               : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 68 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 415 "matrizDiagonal.c"
      memcpy (b_23 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_18, 2)) - 1), b_20, 3);
      /* Line: 65        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 65 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 420 "matrizDiagonal.c"
      cob_add_int (&f_19, 1, 0);
    }
    /* Line: 64        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 64 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 426 "matrizDiagonal.c"
    cob_add_int (&f_18, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 72        : Section   SUMAR-DIAGONAL          : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
  l_12:;
#line 72 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  SECTION_SUMAR__DIAGONAL:	cob_nop ();
#line 438 "matrizDiagonal.c"

  /* Line: 73        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 73 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 443 "matrizDiagonal.c"
  memcpy (b_18, "01", 2);
  for (;;)
  {
    /* Line: 73        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 73 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 450 "matrizDiagonal.c"
    if (((int)memcmp (b_18, b_17, 2) > 0))
      break;

    /* Line: 74        : ADD                : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 74 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 457 "matrizDiagonal.c"
    cob_add_int (&f_22, cob_get_numdisp (b_23 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_18, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_18, 2)) - 1), 3), 0);
    /* Line: 73        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 73 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
    cob_nop ();
#line 462 "matrizDiagonal.c"
    cob_add_int (&f_18, 1, 0);
  }

  /* Line: 76        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrizDiagonal.cbl */
#line 76 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 469 "matrizDiagonal.c"
  cob_display (0, 1, 2, &c_17, &f_22);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  MATRICES_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field N */
#line 7 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 526 "matrizDiagonal.c"
  memset (b_17, 48, 2);

  /* initialize field I */
#line 8 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 532 "matrizDiagonal.c"
  memset (b_18, 48, 2);

  /* initialize field J */
#line 9 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 538 "matrizDiagonal.c"
  memset (b_19, 48, 2);

  /* initialize field NUM */
#line 10 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 544 "matrizDiagonal.c"
  memset (b_20, 48, 3);

  /* initialize field WS-OPCION */
#line 11 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 550 "matrizDiagonal.c"
  *(b_21) = 48;

  /* initialize field ACUMULADOR */
#line 12 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
  cob_nop ();
#line 556 "matrizDiagonal.c"
  memset (b_22, 48, 4);

  /* initialize ROW-1: init first record */
  {
    /* initialize COL-1: init first record */
    {
      /* initialize field ELEM-1 */
#line 18 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrizDiagonal.cbl"
      cob_nop ();
#line 566 "matrizDiagonal.c"
      memset (b_23, 48, 3);
      /* initialize COL-1: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_23;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-1:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-1:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-1:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-1:     9 thru 10 */
      }
    }
    /* initialize ROW-1: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_23;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-1:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-1:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-1:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-1:     9 thru 10 */
    }
  }


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'MATRICES' */

/* Initialize module structure for MATRICES */
static void MATRICES_module_init (cob_module *module)
{
  module->module_name = "MATRICES";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MATRICES;
  module->module_cancel.funcptr = (void *(*)())MATRICES_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

