/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
/* Generated at           Jul 18 2025 02:24:27 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\matrices/includes -g -fmf -o matrices.exe C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Jul 18 2025 02:24:27"
#define  COB_MODULE_DATE		20250718
#define  COB_MODULE_TIME		22427

/* Global variables */
#include "matrices.c.h"

/* Function prototypes */

static int		MATRICES ();
static int		MATRICES_ (const int);
static void		MATRICES_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (MATRICES ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MATRICES' */

/* ENTRY 'MATRICES' */

static int
MATRICES ()
{
  return MATRICES_ (0);
}

static int
MATRICES_ (const int entry)
{
  /* Program local variables */
  #include "matrices.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 29        : Entry     MATRICES                : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
  l_2:;
#line 29 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  ENTRY_MATRICES:	cob_nop ();
#line 109 "matrices.c"

  /* Line: 29        : Paragraph MAIN-SECTION            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 29 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  PARAGRAPH_MAIN__SECTION_l_4:	cob_nop ();
#line 114 "matrices.c"

  /* Line: 31        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 31 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 119 "matrices.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 32        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 32 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 125 "matrices.c"
  cob_accept (&f_17);

  /* Line: 33        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 33 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 131 "matrices.c"
  cob_display (0, 1, 1, &c_2);

  /* Line: 34        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 34 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 137 "matrices.c"
  cob_accept (&f_18);

  /* Line: 36        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 36 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 143 "matrices.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 37        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 37 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 149 "matrices.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 37        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 37 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 156 "matrices.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 38        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 38 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 163 "matrices.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 38        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 38 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 170 "matrices.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 39        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 39 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 177 "matrices.c"
      cob_display (0, 1, 5, &c_4, &f_19, &c_5, &f_20, &c_6);

      /* Line: 40        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 40 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 183 "matrices.c"
      cob_accept (&f_21);

      /* Line: 41        : MOVE               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 41 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 189 "matrices.c"
      memcpy (b_22 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), b_21, 3);
      /* Line: 38        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 38 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 194 "matrices.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 37        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 37 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 200 "matrices.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Line: 45        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 45 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 207 "matrices.c"
  cob_display (0, 1, 1, &c_7);

  /* Line: 46        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 46 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 213 "matrices.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 46        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 46 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 220 "matrices.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 47        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 47 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 227 "matrices.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 47        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 47 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 234 "matrices.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 48        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 48 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 241 "matrices.c"
      cob_display (0, 1, 5, &c_4, &f_19, &c_5, &f_20, &c_8);

      /* Line: 49        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 49 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 247 "matrices.c"
      cob_accept (&f_21);

      /* Line: 50        : MOVE               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 50 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 253 "matrices.c"
      memcpy (b_26 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), b_21, 3);
      /* Line: 47        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 47 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 258 "matrices.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 46        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 46 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 264 "matrices.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Line: 54        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 54 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 271 "matrices.c"
  cob_display (0, 1, 1, &c_9);

  /* Line: 55        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 55 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 277 "matrices.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 55        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 55 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 284 "matrices.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 56        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 56 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 291 "matrices.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 56        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 56 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 298 "matrices.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 57        : COMPUTE            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 57 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 305 "matrices.c"
      cob_decimal_set_field (d_0, COB_SET_FLD (f0, 3, b_22 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_3));
      cob_decimal_set_field (d_1, COB_SET_FLD (f0, 3, b_26 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_3));
      cob_decimal_add (d_0, d_1);
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 3, b_30 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_3), 0);

      /* Line: 58        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 58 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 314 "matrices.c"
      cob_display (0, 1, 6, &c_10, &f_19, &c_5, &f_20, &c_11, COB_SET_FLD (f0, 3, b_30 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_3));
      /* Line: 56        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 56 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 319 "matrices.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 55        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 55 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 325 "matrices.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Line: 62        : STOP RUN           : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 62 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 332 "matrices.c"
  cob_stop_run (b_2);

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  MATRICES_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field N */
#line 7 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 385 "matrices.c"
  memset (b_17, 48, 2);

  /* initialize field M */
#line 8 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 391 "matrices.c"
  memset (b_18, 48, 2);

  /* initialize field I */
#line 9 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 397 "matrices.c"
  memset (b_19, 48, 2);

  /* initialize field J */
#line 10 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 403 "matrices.c"
  memset (b_20, 48, 2);

  /* initialize field NUM */
#line 11 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 409 "matrices.c"
  memset (b_21, (unsigned char)'0', 3);

  /* initialize ROW-1: init first record */
  {
    /* initialize COL-1: init first record */
    {
      /* initialize field ELEM-1 */
#line 16 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 419 "matrices.c"
      memset (b_22, 48, 3);
      /* initialize COL-1: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_22;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-1:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-1:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-1:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-1:     9 thru 10 */
      }
    }
    /* initialize ROW-1: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_22;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-1:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-1:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-1:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-1:     9 thru 10 */
    }
  }

  /* initialize ROW-2: init first record */
  {
    /* initialize COL-2: init first record */
    {
      /* initialize field ELEM-2 */
#line 21 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 447 "matrices.c"
      memset (b_26, 48, 3);
      /* initialize COL-2: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_26;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-2:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-2:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-2:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-2:     9 thru 10 */
      }
    }
    /* initialize ROW-2: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_26;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-2:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-2:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-2:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-2:     9 thru 10 */
    }
  }

  /* initialize ROW-3: init first record */
  {
    /* initialize COL-3: init first record */
    {
      /* initialize field ELEM-3 */
#line 26 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 475 "matrices.c"
      memset (b_30, 48, 3);
      /* initialize COL-3: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_30;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-3:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-3:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-3:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-3:     9 thru 10 */
      }
    }
    /* initialize ROW-3: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_30;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-3:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-3:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-3:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-3:     9 thru 10 */
    }
  }


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'MATRICES' */

/* Initialize module structure for MATRICES */
static void MATRICES_module_init (cob_module *module)
{
  module->module_name = "MATRICES";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MATRICES;
  module->module_cancel.funcptr = (void *(*)())MATRICES_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

