/* Generated by           cobc 3.2.0 */
/* Generated from         C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
/* Generated at           Jul 18 2025 05:41:12 */
/* GnuCOBOL build date    Nov 27 2024 17:43:47 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        C:\msys64\mingw64\bin\cobc.exe -x -I C:\msys64\home\lopez\COBOL\matrices/includes -g -fmf -o matrices.exe C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Jul 18 2025 05:41:12"
#define  COB_MODULE_DATE		20250718
#define  COB_MODULE_TIME		54112

/* Global variables */
#include "matrices.c.h"

/* Function prototypes */

static int		MATRICES ();
static int		MATRICES_ (const int);
static void		MATRICES_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (MATRICES ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MATRICES' */

/* ENTRY 'MATRICES' */

static int
MATRICES ()
{
  return MATRICES_ (0);
}

static int
MATRICES_ (const int entry)
{
  /* Program local variables */
  #include "matrices.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 32        : Entry     MATRICES                : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
  l_2:;
#line 32 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  ENTRY_MATRICES:	cob_nop ();
#line 109 "matrices.c"

  /* Line: 32        : Section   MAIN-PROGRAM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 32 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  SECTION_MAIN__PROGRAM:	cob_nop ();
#line 114 "matrices.c"

  /* Line: 33        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 33 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 119 "matrices.c"
  for (;;)
  {
    /* Line: 33        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 33 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 125 "matrices.c"
    if (((int)cob_cmp_numdisp (b_22, 1, 4LL, 0) == 0))
      break;

    /* Line: 34        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 34 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 132 "matrices.c"
    /* PERFORM MAIN-MENU */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 6;
    frame_ptr->return_address_ptr = &&l_14;
    goto l_6;
    l_14:
    frame_ptr--;

    /* Line: 35        : EVALUATE           : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 35 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 146 "matrices.c"

    /* Line: 36        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 36 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 151 "matrices.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 1LL, 0) == 0))
    {

      /* Line: 37        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 37 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 159 "matrices.c"
      /* PERFORM DIMENSIONAR-MATRICES */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 8;
      frame_ptr->return_address_ptr = &&l_15;
      goto l_8;
      l_15:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 38        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 38 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 175 "matrices.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 2LL, 0) == 0))
    {

      /* Line: 39        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 39 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 183 "matrices.c"
      /* PERFORM CARGAR-MATRICES */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 10;
      frame_ptr->return_address_ptr = &&l_16;
      goto l_10;
      l_16:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 40        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 40 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 199 "matrices.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 3LL, 0) == 0))
    {

      /* Line: 41        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 41 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 207 "matrices.c"
      /* PERFORM SUMAR-MATRICES */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 12;
      frame_ptr->return_address_ptr = &&l_17;
      goto l_12;
      l_17:
      frame_ptr--;
      goto l_5;
    }

    /* Line: 42        : WHEN               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 42 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 223 "matrices.c"

    if (((int)cob_cmp_numdisp (b_22, 1, 4LL, 0) == 0))
    {

      /* Line: 43        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 43 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 231 "matrices.c"
      cob_display (0, 1, 1, &c_1);
      goto l_5;
    }

    /* WHEN OTHER */

    /* Line: 45        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 45 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 241 "matrices.c"
    cob_display (0, 1, 1, &c_2);

    /* End EVALUATE */
    l_5:;
  }

  /* Line: 51        : Section   MAIN-MENU               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
  l_6:;
#line 51 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  SECTION_MAIN__MENU:	cob_nop ();
#line 252 "matrices.c"

  /* Line: 52        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 52 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 257 "matrices.c"
  cob_display (0, 1, 1, &c_3);

  /* Line: 53        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 53 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 263 "matrices.c"
  cob_display (0, 1, 1, &c_4);

  /* Line: 54        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 54 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 269 "matrices.c"
  cob_display (0, 1, 1, &c_5);

  /* Line: 55        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 55 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 275 "matrices.c"
  cob_display (0, 1, 1, &c_6);

  /* Line: 56        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 56 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 281 "matrices.c"
  cob_display (0, 1, 1, &c_7);

  /* Line: 57        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 57 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 287 "matrices.c"
  cob_display (0, 0, 1, &c_8);

  /* Line: 58        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 58 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 293 "matrices.c"
  cob_accept (&f_22);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 61        : Section   DIMENSIONAR-MATRICES    : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
  l_8:;
#line 61 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  SECTION_DIMENSIONAR__MATRICES:	cob_nop ();
#line 304 "matrices.c"

  /* Line: 62        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 62 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 309 "matrices.c"
  for (;;)
  {
    /* Line: 62        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 62 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 315 "matrices.c"
    if ((((int)cob_cmp_numdisp (b_17, 2, 1LL, 0) >= 0) && 
        ((int)cob_cmp_numdisp (b_17, 2, 10LL, 0) <= 0)))
      break;

    /* Line: 63        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 63 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 323 "matrices.c"
    cob_display (0, 1, 1, &c_9);

    /* Line: 64        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 64 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 329 "matrices.c"
    cob_accept (&f_17);

    /* Line: 65        : IF                 : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 65 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 335 "matrices.c"
    if ((((int)cob_cmp_numdisp (b_17, 2, 10LL, 0) > 0) || 
        ((int)cob_cmp_numdisp (b_17, 2, 1LL, 0) < 0)))
    {

      /* Line: 66        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 66 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 343 "matrices.c"
      cob_display (0, 1, 1, &c_10);
    }
  }

  /* Line: 70        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 70 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 351 "matrices.c"
  for (;;)
  {
    /* Line: 70        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 70 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 357 "matrices.c"
    if ((((int)cob_cmp_numdisp (b_18, 2, 1LL, 0) >= 0) && 
        ((int)cob_cmp_numdisp (b_18, 2, 10LL, 0) <= 0)))
      break;

    /* Line: 71        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 71 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 365 "matrices.c"
    cob_display (0, 1, 1, &c_11);

    /* Line: 72        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 72 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 371 "matrices.c"
    cob_accept (&f_18);

    /* Line: 73        : IF                 : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 73 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 377 "matrices.c"
    if ((((int)cob_cmp_numdisp (b_18, 2, 10LL, 0) > 0) || 
        ((int)cob_cmp_numdisp (b_18, 2, 1LL, 0) < 0)))
    {

      /* Line: 74        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 74 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 385 "matrices.c"
      cob_display (0, 1, 1, &c_10);
    }
  }

  /* Line: 77        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 77 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 393 "matrices.c"
  cob_display (0, 1, 4, &c_12, &f_17, &c_13, &f_18);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 79        : Section   CARGAR-MATRICES         : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
  l_10:;
#line 79 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  SECTION_CARGAR__MATRICES:	cob_nop ();
#line 404 "matrices.c"

  /* Line: 80        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 80 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 409 "matrices.c"
  cob_display (0, 1, 1, &c_14);

  /* Line: 81        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 81 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 415 "matrices.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 81        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 81 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 422 "matrices.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 82        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 82 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 429 "matrices.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 82        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 82 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 436 "matrices.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 83        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 83 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 443 "matrices.c"
      cob_display (0, 1, 5, &c_15, &f_19, &c_16, &f_20, &c_17);

      /* Line: 84        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 84 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 449 "matrices.c"
      cob_accept (&f_21);

      /* Line: 85        : MOVE               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 85 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 455 "matrices.c"
      memcpy (b_24 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), b_21, 3);
      /* Line: 82        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 82 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 460 "matrices.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 81        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 81 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 466 "matrices.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Line: 90        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 90 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 473 "matrices.c"
  cob_display (0, 1, 1, &c_18);

  /* Line: 91        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 91 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 479 "matrices.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 91        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 91 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 486 "matrices.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 92        : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 92 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 493 "matrices.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 92        : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 92 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 500 "matrices.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 93        : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 93 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 507 "matrices.c"
      cob_display (0, 1, 5, &c_15, &f_19, &c_16, &f_20, &c_19);

      /* Line: 94        : ACCEPT             : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 94 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 513 "matrices.c"
      cob_accept (&f_21);

      /* Line: 95        : MOVE               : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 95 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 519 "matrices.c"
      memcpy (b_28 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), b_21, 3);
      /* Line: 92        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 92 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 524 "matrices.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 91        : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 91 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 530 "matrices.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 99        : Section   SUMAR-MATRICES          : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
  l_12:;
#line 99 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  SECTION_SUMAR__MATRICES:	cob_nop ();
#line 542 "matrices.c"

  /* Line: 100       : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 100 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 547 "matrices.c"
  cob_display (0, 1, 1, &c_20);

  /* Line: 101       : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 101 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 553 "matrices.c"
  memcpy (b_19, "01", 2);
  for (;;)
  {
    /* Line: 101       : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 101 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 560 "matrices.c"
    if (((int)memcmp (b_19, b_17, 2) > 0))
      break;

    /* Line: 102       : PERFORM            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 102 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 567 "matrices.c"
    memcpy (b_20, "01", 2);
    for (;;)
    {
      /* Line: 102       : UNTIL              : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 102 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 574 "matrices.c"
      if (((int)memcmp (b_20, b_18, 2) > 0))
        break;

      /* Line: 103       : COMPUTE            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 103 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 581 "matrices.c"
      cob_decimal_set_field (d_0, COB_SET_FLD (f0, 3, b_24 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4));
      cob_decimal_set_field (d_1, COB_SET_FLD (f0, 3, b_28 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4));
      cob_decimal_add (d_0, d_1);
      cob_decimal_get_field (d_0, COB_SET_FLD (f0, 3, b_32 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4), 0);

      /* Line: 104       : DISPLAY            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 104 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 590 "matrices.c"
      cob_display (0, 1, 6, &c_21, &f_19, &c_16, &f_20, &c_22, COB_SET_FLD (f0, 3, b_32 + 3LL * ((cob_s64_t)(cob_get_numdisp (b_20, 2)) - 1) + 30LL * ((cob_s64_t)(cob_get_numdisp (b_19, 2)) - 1), &a_4));
      /* Line: 102       : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 102 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 595 "matrices.c"
      cob_add_int (&f_20, 1, 0);
    }
    /* Line: 101       : VARYING            : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 101 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
    cob_nop ();
#line 601 "matrices.c"
    cob_add_int (&f_19, 1, 0);
  }

  /* Line: 107       : STOP RUN           : C:\msys64\home\lopez\COBOL\matrices\matrices.cbl */
#line 107 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 608 "matrices.c"
  cob_stop_run (b_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  MATRICES_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field N */
#line 7 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 665 "matrices.c"
  memset (b_17, 48, 2);

  /* initialize field M */
#line 8 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 671 "matrices.c"
  memset (b_18, 48, 2);

  /* initialize field I */
#line 9 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 677 "matrices.c"
  memset (b_19, 48, 2);

  /* initialize field J */
#line 10 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 683 "matrices.c"
  memset (b_20, 48, 2);

  /* initialize field NUM */
#line 11 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 689 "matrices.c"
  memset (b_21, 48, 3);

  /* initialize field WS-OPCION */
#line 12 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 695 "matrices.c"
  *(b_22) = 48;

  /* initialize field SEPARADOR */
#line 13 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
  cob_nop ();
#line 701 "matrices.c"
  memset (b_23, (unsigned char)' ', 80);

  /* initialize ROW-1: init first record */
  {
    /* initialize COL-1: init first record */
    {
      /* initialize field ELEM-1 */
#line 19 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 711 "matrices.c"
      memset (b_24, 48, 3);
      /* initialize COL-1: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_24;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-1:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-1:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-1:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-1:     9 thru 10 */
      }
    }
    /* initialize ROW-1: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_24;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-1:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-1:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-1:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-1:     9 thru 10 */
    }
  }

  /* initialize ROW-2: init first record */
  {
    /* initialize COL-2: init first record */
    {
      /* initialize field ELEM-2 */
#line 24 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 739 "matrices.c"
      memset (b_28, 48, 3);
      /* initialize COL-2: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_28;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-2:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-2:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-2:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-2:     9 thru 10 */
      }
    }
    /* initialize ROW-2: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_28;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-2:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-2:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-2:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-2:     9 thru 10 */
    }
  }

  /* initialize ROW-3: init first record */
  {
    /* initialize COL-3: init first record */
    {
      /* initialize field ELEM-3 */
#line 29 "C:\\msys64\\home\\lopez\\COBOL\\matrices\\matrices.cbl"
      cob_nop ();
#line 767 "matrices.c"
      memset (b_32, 48, 3);
      /* initialize COL-3: copy initialized record to later occurrences */
      {
        cob_u8_ptr b_ptr = b_32;
        memcpy (b_ptr +      3, b_ptr,      3);	/* COL-3:     2 thru 2 */
        memcpy (b_ptr +      6, b_ptr,      6);	/* COL-3:     3 thru 4 */
        memcpy (b_ptr +     12, b_ptr,     12);	/* COL-3:     5 thru 8 */
        memcpy (b_ptr +     24, b_ptr,      6);	/* COL-3:     9 thru 10 */
      }
    }
    /* initialize ROW-3: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_32;
      memcpy (b_ptr +     30, b_ptr,     30);	/* ROW-3:     2 thru 2 */
      memcpy (b_ptr +     60, b_ptr,     60);	/* ROW-3:     3 thru 4 */
      memcpy (b_ptr +    120, b_ptr,    120);	/* ROW-3:     5 thru 8 */
      memcpy (b_ptr +    240, b_ptr,     60);	/* ROW-3:     9 thru 10 */
    }
  }


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'MATRICES' */

/* Initialize module structure for MATRICES */
static void MATRICES_module_init (cob_module *module)
{
  module->module_name = "MATRICES";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MATRICES;
  module->module_cancel.funcptr = (void *(*)())MATRICES_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

